#!/usr/bin/env bash
# a Bash script that displays Best School 10times, but for the 9th iteration, displays Best School and then Hi
i=0
while [ $i -le 9 ]
do
	echo "Best School"
	if [ $i -eq 8 ];
	then
		echo "Hi"
	fi
	((i++))
done
