#!/usr/bin/env bash
# a Bash script that displays Best School 10times, but for the 9th iteration, displays Best School and then Hi
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ];
	then
		echo "bad luck"
	elif [ $i -eq 8 ];
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
