#!/usr/bin/env bash
#a Bash script that configures an Ubuntu server with the below requirements
hosts_file="/etc/hosts"
echo "127.0.0.2 localhost" | sudo tee -a $hosts_file > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a $hosts_file > /dev/null
