#!/usr/bin/env bash
# nginx conf

if ! id -u nginx &>/dev/null; then
	useradd -s /sbin/nologin -r nginx
fi
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

nginx -s reload
